name: hasanati
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  algolia: 1.1.1
  connectivity: ^3.0.0
  audio_session: 0.1.16
  audioplayers: ^5.2.1
  audioplayers_android: ^4.0.3
  audioplayers_web: ^4.1.0
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  carousel_slider: 4.2.1
  cloud_firestore: 4.8.0
  cloud_firestore_platform_interface: 5.15.0
  cloud_firestore_web: 3.6.0
  cloud_functions: 4.3.2
  cloud_functions_platform_interface: 5.4.2
  cloud_functions_web: 4.5.2
  csv: 5.0.1
  easy_debounce: 2.0.1
  equatable: 2.0.5
  file_picker: 6.1.1
  firebase_auth: 4.6.2
  firebase_auth_platform_interface: 6.15.2
  firebase_auth_web: 5.5.2
  firebase_core: 2.13.1
  firebase_core_platform_interface: 4.8.0
  firebase_core_web: 2.5.0
  firebase_messaging: 14.6.2
  firebase_messaging_platform_interface: 4.5.2
  firebase_messaging_web: 3.5.2
  firebase_performance: 0.9.2+2
  firebase_performance_platform_interface: 0.1.4+2
  firebase_performance_web: 0.1.4+2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_html: 3.0.0-alpha.5
  flutter_plugin_android_lifecycle: 2.0.17
  flutter_secure_storage: 8.0.0
  flutter_sliding_box: ^1.1.3
  flutter_svg: 2.0.9
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  geocoding: ^2.1.1
  geocoding_android: ^2.1.2
  geocoding_ios: ^2.1.0
  geocoding_platform_interface: ^2.0.0
  geolocator: 10.0.1
  geolocator_android: 4.2.4
  geolocator_apple: 2.2.7
  geolocator_platform_interface: 4.0.8
  geolocator_web: 2.1.6
  go_router: 7.1.1
  google_fonts: 4.0.3
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  infinite_scroll_pagination:
    git:
      url: https://github.com/FlutterFlow/infinite_scroll_pagination.git
      ref: develop
  intl: 0.18.1
  json_path: 0.6.2
  just_audio: ^0.9.29
  just_audio_platform_interface: ^4.2.1
  just_audio_web: 0.4.8
  lottie: 2.7.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  percent_indicator: 4.2.2
  permission_handler: 10.0.0
  plugin_platform_interface: 2.1.6
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sliding_up_panel: ^2.0.0+1
  sqflite: 2.2.6
  stream_transform: 2.1.0
  synchronized: 3.1.0
  text_search: 1.0.1
  timeago: 3.2.2
  universal_io: 2.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1
  webviewx_plus: 0.3.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/images/app_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: "P001"
      fonts:
        - asset: assets/fonts/QCF_P001.TTF
    - family: "P002"
      fonts:
        - asset: assets/fonts/QCF_P002.ttf
    - family: "P003"
      fonts:
        - asset: assets/fonts/QCF_P003.TTF
    - family: "P004"
      fonts:
        - asset: assets/fonts/QCF_P004.TTF
    - family: "P005"
      fonts:
        - asset: assets/fonts/QCF_P005.TTF
    - family: "P006"
      fonts:
        - asset: assets/fonts/QCF_P006.TTF
    - family: "P007"
      fonts:
        - asset: assets/fonts/QCF_P007.TTF
    - family: "P008"
      fonts:
        - asset: assets/fonts/QCF_P008.TTF
    - family: "P009"
      fonts:
        - asset: assets/fonts/QCF_P009.TTF
    - family: "P010"
      fonts:
        - asset: assets/fonts/QCF_P010.TTF
    - family: "P011"
      fonts:
        - asset: assets/fonts/QCF_P011.TTF
    - family: "P012"
      fonts:
        - asset: assets/fonts/QCF_P012.TTF
    - family: "P013"
      fonts:
        - asset: assets/fonts/QCF_P013.TTF
    - family: "P014"
      fonts:
        - asset: assets/fonts/QCF_P014.TTF
    - family: "P015"
      fonts:
        - asset: assets/fonts/QCF_P015.TTF
    - family: "P016"
      fonts:
        - asset: assets/fonts/QCF_P016.TTF
    - family: "P017"
      fonts:
        - asset: assets/fonts/QCF_P017.TTF
    - family: "P018"
      fonts:
        - asset: assets/fonts/QCF_P018.TTF
    - family: "P019"
      fonts:
        - asset: assets/fonts/QCF_P019.TTF
    - family: "P020"
      fonts:
        - asset: assets/fonts/QCF_P020.TTF
    - family: "P021"
      fonts:
        - asset: assets/fonts/QCF_P021.TTF
    - family: "P022"
      fonts:
        - asset: assets/fonts/QCF_P022.TTF
    - family: "P023"
      fonts:
        - asset: assets/fonts/QCF_P023.TTF
    - family: "P024"
      fonts:
        - asset: assets/fonts/QCF_P024.TTF
    - family: "P025"
      fonts:
        - asset: assets/fonts/QCF_P025.TTF
    - family: "P026"
      fonts:
        - asset: assets/fonts/QCF_P026.TTF
    - family: "P027"
      fonts:
        - asset: assets/fonts/QCF_P027.TTF
    - family: "P028"
      fonts:
        - asset: assets/fonts/QCF_P028.TTF
    - family: "P029"
      fonts:
        - asset: assets/fonts/QCF_P029.TTF
    - family: "P030"
      fonts:
        - asset: assets/fonts/QCF_P030.TTF
    - family: "P031"
      fonts:
        - asset: assets/fonts/QCF_P031.TTF
    - family: "P032"
      fonts:
        - asset: assets/fonts/QCF_P032.TTF
    - family: "P033"
      fonts:
        - asset: assets/fonts/QCF_P033.TTF
    - family: "P034"
      fonts:
        - asset: assets/fonts/QCF_P034.TTF
    - family: "quranFont"
      fonts:
        - asset: assets/fonts/Al_Majeed_Quranic_Font_shiped_(1).ttf
    - family: "quran2"
      fonts:
        - asset: assets/fonts/Al_Mushaf_Quran_(2).ttf
    - family: "qurankarim114"
      fonts:
        - asset: assets/fonts/Quran_karim_114.ttf
    - family: "QCF_BSML"
      fonts:
        - asset: assets/fonts/QCF_BSML.TTF
    - family: "Muhammadi "
      fonts:
        - asset: assets/fonts/MUHAMMADI_QURANIC_FONT.ttf
    - family: "Fredoka"
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
    - family: "CriqueGrotesk"
      fonts:
        - asset: assets/fonts/CriqueGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/CriqueGrotesk.ttf
        - asset: assets/fonts/CriqueGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/CriqueGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/CriqueGrotesk-Black.ttf
          weight: 900
    - family: '72'
      fonts:
        - asset: assets/fonts/72-Light.ttf
          weight: 300
        - asset: assets/fonts/72-Regular.ttf
        - asset: assets/fonts/72-Italic.ttf
          style: italic
        - asset: assets/fonts/72-Semibold.ttf
          weight: 600
        - asset: assets/fonts/72-Bold.ttf
          weight: 700
        - asset: assets/fonts/72-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/72-Black.ttf
          weight: 900

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
